version: "3.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_stub
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_stub
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: channelA:1:1, channelB:1:1
  
  mongo:
    container_name: mongo_stub
    image: mongo
    ports:
      - 27017:27007 
        
  producer:
    build: ./ftpStarbeatArchive
    container_name: microservizio-producer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - mongo
    links:
      - kafka
      - mongo
    environment:
      PRODUCER_TOPIC: channelA
      CONSUMER_TOPIC: channelB
 
 
      