version: "3.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
  producer:
    image: ftp-starbeat-archive:1.0
    container_name: microservice-producer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kafka
    links:
      - kafka:kafka
    environment:
      PRODUCER_TOPIC: meter
      CONSUMER_TOPIC: none
      
  consumer:
    image: ftp-starbeat-archive:1.0
    container_name: microservice-consumer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - kafka
    links:
      - kafka:kafka
    environment:
      PRODUCER_TOPIC: none
      CONSUMER_TOPIC: meter
 
      